###### 1
plot.new()
plot(df582$ts, df582$Force.Sum.Actual, type="l", pch=1, col=3, xlab="Time(PQ0582)",ylab="",ylim=c(min(df582$Force.Sum.Actual),max(df582$Force.Sum.Actual)),main="Force.Sum.Actual")
mtext("Force.Sum.Actual",side=2,line=2,col=3)
par(new=T)
plot(df582$Thickness.Deviation.Absolut, axes=F, xlab="",ylab="",ylim=c(-3.5,3.5), type="l", pch=2, col=4 )
axis(side=4)
mtext("Thickness",side=4,line=2,col=4)
abline(h = 3, col = "red")
abline(h = -3, col = "red")

###### 2
plot.new()
plot(df582$ts, df582$DS.U_Pressure.Actual, type="l", pch=1, col=3, xlab="Time(PQ0582)",ylab="",ylim=c(min(df582$DS.U_Pressure.Actual),max(df582$DS.U_Pressure.Actual)),main="DS.U_Pressure.Actual")
mtext("DS.U_Pressure.Actual",side=2,line=2,col=3)
par(new=T)
plot(df582$Thickness.Deviation.Absolut, axes=F, xlab="",ylab="",ylim=c(-3.5,3.5), type="l", pch=2, col=4 )
axis(side=4)
mtext("Thickness",side=4,line=2,col=4)
abline(h = 3, col = "red")
abline(h = -3, col = "red")

###### 3
plot.new()
plot(df582$ts, df582$Bending.Pressure.Measured.Negative, type="l", pch=1, col=3, xlab="Time(PQ0582)",ylab="",ylim=c(min(df582$Bending.Pressure.Measured.Negative),max(df582$Bending.Pressure.Measured.Negative)),main="Bending.Pressure.Measured.Negative")
mtext("Bending.Pressure.Measured.Negative",side=2,line=2,col=3)
par(new=T)
plot(df582$Thickness.Deviation.Absolut, axes=F, xlab="",ylab="",ylim=c(-3.5,3.5), type="l", pch=2, col=4 )
axis(side=4)
mtext("Thickness",side=4,line=2,col=4)
abline(h = 3, col = "red")
abline(h = -3, col = "red")

###### 4
plot.new()
plot(df582$ts, df582$Bending.U.Measured.Positive, type="l", pch=1, col=3, xlab="Time(PQ0582)",ylab="",ylim=c(min(df582$Bending.U.Measured.Positive),max(df582$Bending.U.Measured.Positive)),main="Bending.U.Measured.Positive")
mtext("Bending.U.Measured.Positive",side=2,line=2,col=3)
par(new=T)
plot(df582$Thickness.Deviation.Absolut, axes=F, xlab="",ylab="",ylim=c(-3.5,3.5), type="l", pch=2, col=4 )
axis(side=4)
mtext("Thickness",side=4,line=2,col=4)
abline(h = 3, col = "red")
abline(h = -3, col = "red")

###### 5
plot.new()
plot(df582$ts, df582$Speed.Mill.Actual, type="l", pch=1, col=3, xlab="Time(PQ0582)",ylab="",ylim=c(min(df582$Speed.Mill.Actual),max(df582$Speed.Mill.Actual)),main="Speed.Mill.Actual")
mtext("Speed.Mill.Actual",side=2,line=2,col=3)
par(new=T)
plot(df582$Thickness.Deviation.Absolut, axes=F, xlab="",ylab="",ylim=c(-3.5,3.5), type="l", pch=2, col=4 )
axis(side=4)
mtext("Thickness",side=4,line=2,col=4)
abline(h = 3, col = "red")
abline(h = -3, col = "red")

###### 6
plot.new()
plot(df582$ts, df582$Speed.Exit.Actual, type="l", pch=1, col=3, xlab="Time(PQ0582)",ylab="",ylim=c(min(df582$Speed.Exit.Actual),max(df582$Speed.Exit.Actual)),main="Speed.Exit.Actual")
mtext("Speed.Exit.Actual",side=2,line=2,col=3)
par(new=T)
plot(df582$Thickness.Deviation.Absolut, axes=F, xlab="",ylab="",ylim=c(-3.5,3.5), type="l", pch=2, col=4 )
axis(side=4)
mtext("Thickness",side=4,line=2,col=4)
abline(h = 3, col = "red")
abline(h = -3, col = "red")

###### 7
plot.new()
plot(df582$ts, df582$dh_raw, type="l", pch=1, col=3, xlab="Time(PQ0582)",ylab="",ylim=c(min(df582$dh_raw),max(df582$dh_raw)),main="dh_raw")
mtext("dh_raw",side=2,line=2,col=3)
par(new=T)
plot(df582$Thickness.Deviation.Absolut, axes=F, xlab="",ylab="",ylim=c(-3.5,3.5), type="l", pch=2, col=4 )
axis(side=4)
mtext("Thickness",side=4,line=2,col=4)
abline(h = 3, col = "red")
abline(h = -3, col = "red")

###### 8
plot.new()
plot(df582$ts, df582$Tension.Exit.Actual, type="l", pch=1, col=3, xlab="Time(PQ0582)",ylab="",ylim=c(min(df582$Tension.Exit.Actual),max(df582$Tension.Exit.Actual)),main="Tension.Exit.Actual")
mtext("Tension.Exit.Actual",side=2,line=2,col=3)
par(new=T)
plot(df582$Thickness.Deviation.Absolut, axes=F, xlab="",ylab="",ylim=c(-3.5,3.5), type="l", pch=2, col=4 )
axis(side=4)
mtext("Thickness",side=4,line=2,col=4)
abline(h = 3, col = "red")
abline(h = -3, col = "red")

###### 9
plot.new()
plot(df582$ts, df582$Thickness.Exit.Delta, type="l", pch=1, col=3, xlab="Time(PQ0582)",ylab="",ylim=c(min(df582$Thickness.Exit.Delta),max(df582$Thickness.Exit.Delta)),main="Thickness.Exit.Delta")
mtext("Thickness.Exit.Delta",side=2,line=2,col=3)
par(new=T)
plot(df582$Thickness.Deviation.Absolut, axes=F, xlab="",ylab="",ylim=c(-3.5,3.5), type="l", pch=2, col=4 )
axis(side=4)
mtext("Thickness",side=4,line=2,col=4)
abline(h = 3, col = "red")
abline(h = -3, col = "red")

###### 10
plot.new()
plot(df582$ts, df582$VC.Ctrl.Out, type="l", pch=1, col=3, xlab="Time(PQ0582)",ylab="",ylim=c(min(df582$VC.Ctrl.Out),max(df582$VC.Ctrl.Out)),main="VC.Ctrl.Out")
mtext("VC.Ctrl.Out",side=2,line=2,col=3)
par(new=T)
plot(df582$Thickness.Deviation.Absolut, axes=F, xlab="",ylab="",ylim=c(-3.5,3.5), type="l", pch=2, col=4 )
axis(side=4)
mtext("Thickness",side=4,line=2,col=4)
abline(h = 3, col = "red")
abline(h = -3, col = "red")

###### 11
plot.new()
plot(df582$ts, df582$Flow.Error, type="l", pch=1, col=3, xlab="Time(PQ0582)",ylab="",ylim=c(min(df582$Flow.Error),max(df582$Flow.Error)),main="Flow.Error")
mtext("Flow.Error",side=2,line=2,col=3)
par(new=T)
plot(df582$Thickness.Deviation.Absolut, axes=F, xlab="",ylab="",ylim=c(-3.5,3.5), type="l", pch=2, col=4 )
axis(side=4)
mtext("Thickness",side=4,line=2,col=4)
abline(h = 3, col = "red")
abline(h = -3, col = "red")

###### 12
plot.new()
plot(df582$ts, df582$Oil.Pressure, type="l", pch=1, col=3, xlab="Time(PQ0582)",ylab="",ylim=c(min(df582$Oil.Pressure),max(df582$Oil.Pressure)),main="Oil.Pressure")
mtext("Oil.Pressure",side=2,line=2,col=3)
par(new=T)
plot(df582$Thickness.Deviation.Absolut, axes=F, xlab="",ylab="",ylim=c(-3.5,3.5), type="l", pch=2, col=4 )
axis(side=4)
mtext("Thickness",side=4,line=2,col=4)
abline(h = 3, col = "red")
abline(h = -3, col = "red")

###### 13
plot.new()
plot(df582$ts, df582$Mean.Tension, type="l", pch=1, col=3, xlab="Time(PQ0582)",ylab="",ylim=c(min(df582$Mean.Tension),max(df582$Mean.Tension)),main="Mean.Tension")
mtext("Mean.Tension",side=2,line=2,col=3)
par(new=T)
plot(df582$Thickness.Deviation.Absolut, axes=F, xlab="",ylab="",ylim=c(-3.5,3.5), type="l", pch=2, col=4 )
axis(side=4)
mtext("Thickness",side=4,line=2,col=4)
abline(h = 3, col = "red")
abline(h = -3, col = "red")

